spring.application.name=PeerToPeerLearning
# ---------------------------
# Server Configuration
# ---------------------------
server.port=8080

# ---------------------------
# Database Configuration
# ---------------------------
spring.datasource.url=jdbc:postgresql://localhost:5432/skillswap
spring.datasource.username=skillswap_user
spring.datasource.password=Root@123





jwt.secret.key=thisisthesecretkeyievercreatedinmydevelopmentcareer

# ---------------------------
# Hibernate / JPA
# ---------------------------
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

#---------------------Mail-------------
spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
spring.mail.username=a3f1ff001@smtp-brevo.com
spring.mail.password=kcn08XCjHmVF1Ng9
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.from=lazyleet20@gmail.com



